### ISSUE TITLE
doesn't run by default

### ISSUE THREAD

**Issue by jeroenbaas** [ethanzh/gpx-csv-converter#5]
I can't get this to work out of the box, if I install it using pip install gpx_csv_converter and try to run a file:
```
Traceback (most recent call last):
  File "conv.py", line 1, in <module>
    import gpx_csv_converter
  File "/usr/local/lib/python3.4/dist-packages/gpx_csv_converter/__init__.py", line 18
    raise TypeError(f"The file {input_file_name} does not exist.")
                                                                ^
SyntaxError: invalid syntax
```

I ended up working my way around it by taking the code out, but I don't know why I'm getting this error, assuming this should work without issues.

**Comment by ethanzh** [comment]
What version of Python are you running? My feeling is it may be the f-string syntax that your local Python version can't parse (hence the syntax error)

**Comment by jeroenbaas** [comment]
Python 3.4, which is the latest on Ubuntu on Windows (WSL). It indeed doesn't support the f-string (introduced in 3.6). Would it work if the f-strings would be 
`raise TypeError(f"The file {input_file_name} does not exist.")`
to old style:
`raise TypeError("The file %1 does not exist." % (input_file_name))`

**Comment by ethanzh** [comment]
If you'd like, feel free to open a PR with that change. I think .format() would be better than the % syntax however.

**Comment by ethanzh** [comment]
This has been fixed in the latest commit
