### ISSUE TITLE
Encoding error when writing to csv: bytes-like object required instead of str

### ISSUE THREAD

**Issue by SteampunkIslande** [ethanzh/gpx-csv-converter#8]
In python 3, one should
open(output_file_name, "w", encoding="utf-8", newline="")
at the very end of the script, instead of
open(output_file_name, "w**b**", encoding="utf-8", newline="")

Sorry I don't know how to contribute, I'm new to github

Thanks anyway for this script, it saved me time I don't want to spend learning XML ^^

**Comment by rossbroom99** [comment]
thanks a lot
